import{i,a as E,S as $}from"./assets/vendor-BMHzDZyJ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();i.settings({position:"topRight"});const I="44296746-7471de79088029a055864728c",S="https://pixabay.com/api/",p=async(r,t)=>{const a=`${S}?key=${I}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=15`;try{return(await E.get(a)).data}catch(o){throw console.error("Error fetching images:",o),i.error({title:"Error",message:"Failed to fetch images"}),o}},q=document.getElementById("search-form"),u=document.querySelector(".gallery"),y=document.getElementById("loader"),g=document.getElementById("load-more");let l="",m=1,d=0,c=0,f=null;const v=()=>y.classList.remove("hidden"),h=()=>y.classList.add("hidden"),w=()=>g.classList.remove("hidden"),L=()=>g.classList.add("hidden"),B=({webformatURL:r,largeImageURL:t,tags:a,likes:o,views:e,comments:s,downloads:n})=>`
  <div class="photo-card">
    <a href="${t}" data-lightbox="gallery">
      <img src="${r}" alt="${a}" loading="lazy" />
    </a>
    <div class="info">
      <div class="info-item-wrapper"><p class="info-item"><b>Likes</b></p><p class="info-item">${o}</p></div>
      <div class="info-item-wrapper"><p class="info-item"><b>Views</b></p><p class="info-item">${e}</p></div>
      <div class="info-item-wrapper"><p class="info-item"><b>Comments</b></p><p class="info-item">${s}</p></div>
      <div class="info-item-wrapper"><p class="info-item"><b>Downloads</b></p><p class="info-item">${n}</p></div>
    </div>
  </div>
`,b=r=>{const t=r.map(B).join("");u.insertAdjacentHTML("beforeend",t),f?f.refresh():f=new $(".gallery a",{captionsData:"alt",captionDelay:250});const a=document.querySelector(".gallery .photo-card");if(a){const{height:o}=a.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}},M=async r=>{if(r.preventDefault(),l=r.currentTarget.elements.searchQuery.value.trim(),!l){i.warning({title:"Warning",message:"Please enter a valid search query."});return}m=1,c=0,u.innerHTML="",L(),v();try{const t=await p(l,m);if(h(),!t||t.hits.length===0){i.warning({title:"No results",message:"No images found. Try another query."});return}d=t.totalHits,c+=t.hits.length,i.success({title:"Success",message:`We found ${d} images.`}),b(t.hits),c<d?w():i.info({title:"End",message:"You've reached the end of search results."})}catch{h(),i.error({title:"Error",message:"Something went wrong."})}},O=async()=>{m+=1,v(),L();try{const r=await p(l,m);if(h(),!r||r.hits.length===0){i.info({title:"End",message:"You've reached the end of search results."});return}c+=r.hits.length,b(r.hits),c>=d?i.info({title:"End",message:"You've reached the end of search results."}):w()}catch{h(),i.error({title:"Error",message:"Failed to load more images."})}};q.addEventListener("submit",M);g.addEventListener("click",O);
//# sourceMappingURL=index.js.map
