import{i,a as L,S as b}from"./assets/vendor-DFCQGEf1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();i.settings({position:"topRight"});const E="44296746-7471de79088029a055864728c",I="https://pixabay.com/api/",h=async(r,t)=>{const a=`${I}?key=${E}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=15`;try{return(await L.get(a)).data}catch(o){throw console.error("Error fetching images:",o),i.error({title:"Error",message:"Failed to fetch images"}),o}};let g;const u=document.querySelector(".gallery"),p=()=>document.getElementById("loader").classList.remove("hidden"),m=()=>document.getElementById("loader").classList.add("hidden"),y=()=>document.getElementById("load-more").classList.remove("hidden"),v=()=>document.getElementById("load-more").classList.add("hidden"),$=()=>{u.innerHTML=""},B=({webformatURL:r,largeImageURL:t,tags:a,likes:o,views:e,comments:s,downloads:n})=>`
  <li class="photo-card">
    <a href="${t}" data-lightbox="gallery">
      <img src="${r}" alt="${a}" loading="lazy" />
    </a>
    <div class="info">
      <div class="info-item-wrapper"><p class="info-item"><b>Likes</b></p><p class="info-item">${o}</p></div>
      <div class="info-item-wrapper"><p class="info-item"><b>Views</b></p><p class="info-item">${e}</p></div>
      <div class="info-item-wrapper"><p class="info-item"><b>Comments</b></p><p class="info-item">${s}</p></div>
      <div class="info-item-wrapper"><p class="info-item"><b>Downloads</b></p><p class="info-item">${n}</p></div>
    </div>
  </li>
`,w=r=>{const t=r.map(B).join("");u.insertAdjacentHTML("beforeend",t),g?g.refresh():g=new b(".gallery a",{captionsData:"alt",captionDelay:250});const a=document.querySelector(".gallery .photo-card");if(a){const{height:o}=a.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}},S=document.getElementById("search-form"),q=document.getElementById("load-more");let l="",f=1,d=0,c=0;S.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.currentTarget.elements.searchQuery.value.trim(),!l){i.warning({title:"Warning",message:"Please enter a valid search query."});return}f=1,c=0,$(),v(),p();try{const t=await h(l,f);if(m(),!t||t.hits.length===0){i.warning({title:"No results",message:"No images found. Try another query."});return}d=t.totalHits,c+=t.hits.length,i.success({title:"Success",message:`We found ${d} images.`}),w(t.hits),c<d?y():i.info({title:"End",message:"You've reached the end of search results."})}catch{m(),i.error({title:"Error",message:"Something went wrong."})}});q.addEventListener("click",async()=>{f+=1,p(),v();try{const r=await h(l,f);if(m(),!r||r.hits.length===0){i.info({title:"End",message:"You've reached the end of search results."});return}c+=r.hits.length,w(r.hits),c>=d?i.info({title:"End",message:"You've reached the end of search results."}):y()}catch{m(),i.error({title:"Error",message:"Failed to load more images."})}});
//# sourceMappingURL=index.js.map
